package admin

var defaultSettings = map[string]any{
	"shop_name":               "Simones Shop",
	"shop_description":        "Ihr Online-Shop fuer hochwertige Produkte",
	"shop_email":              "info@simones-shop.de",
	"shop_phone":              "",
	"shop_address":            "",
	"currency":                "EUR",
	"currency_symbol":         "EUR",
	"language":                "de",
	"timezone":                "Europe/Berlin",
	"free_shipping_threshold": 50,
	"default_shipping_cost":   4.99,
	"shipping_countries":      []string{"DE", "AT", "CH"},
	"estimated_delivery_days": "2-4",
	"tax_rate":                19,
	"tax_included":            true,
	"payment_methods":         []string{"stripe", "paypal", "klarna"},
	"guest_checkout":          true,
	"return_days":             30,
	"warranty_years":          2,
	"social_facebook":         "",
	"social_instagram":        "",
	"social_tiktok":           "",
	"social_youtube":          "",
	"meta_title":              "Simones Shop - Hochwertige Produkte online kaufen",
	"meta_description":        "Entdecken Sie hochwertige Produkte zu fairen Preisen.",
	"meta_keywords":           "online shop, kaufen, produkte",
	"ai_chat_enabled":         true,
	"reviews_enabled":         true,
	"wishlist_enabled":        true,
	"newsletter_enabled":      true,
	"automation_policy": map[string]any{
		"catalog_enabled":              true,
		"checkout_enabled":             true,
		"supplier_fulfillment_enabled": true,
		"mailing_enabled":              true,
		"max_retry_attempts":           10,
		"alert_threshold_minutes":      20,
	},
	"trend_policy": map[string]any{
		"default_decision": "review_required",
		"country_defaults": map[string]any{
			"DE": "allow",
			"US": "allow",
		},
		"channel_defaults": map[string]any{
			"tiktok":         "allow",
			"meta":           "allow",
			"youtube_google": "review_required",
			"pinterest":      "review_required",
			"snapchat":       "review_required",
		},
	},
	"growth_budget_policy": map[string]any{
		"scope":       "global",
		"channel":     "all",
		"daily_cap":   2500.0,
		"weekly_cap":  17500.0,
		"monthly_cap": 75000.0,
		"target_mer":  2.5,
		"target_roas": 3.0,
		"hard_stop":   true,
	},
	"growth_kill_switch": map[string]any{
		"checkout":         false,
		"channel_sync":     false,
		"campaign_publish": false,
		"creator_payouts":  false,
	},
	"ugc_generator_policy": map[string]any{
		"enabled":                      true,
		"mode":                         "auto",
		"default_output_pack":          "hero_plus_3",
		"default_audio_mode":           "voice_and_captions",
		"default_aspect_ratio":         "9:16",
		"default_render_lane":          "balanced",
		"preferred_render_provider":    "hybrid",
		"preferred_language":           "de",
		"requires_human_review":        false,
		"max_runs_per_product_per_day": 2,
		"max_autopilot_runs_per_sweep": 4,
		"default_duration_seconds":     15,
		"voice_profile":                "magpie_multilingual",
	},
	"autopilot_ready": false,
}
